if: tag =~ /^release/
language: node_js
node_js:
  - "node"
cache: npm
services:
  - docker
install:
  - npm install -g qiniu-upload-tool
  - npm install
  - npm run build
  - ls ./build
  - qiniu-upload push -z beim -p ./build -b usanode -f workbench -r yes
  - export
  - echo "$DOCKER_PWD" | docker login --username=zindex@muxi --password-stdin registry.cn-hongkong.aliyuncs.com
  - docker build . -t registry.cn-hongkong.aliyuncs.com/muxiauth/workbench_fe:$TRAVIS_TAG
  - docker push registry.cn-hongkong.aliyuncs.com/muxiauth/workbench_fe:$TRAVIS_TAG
script:
  - sh ./afterBuild.sh