if: tag =~ /^release/
language: node_js
node_js:
  - "node"
services:
  - docker
install:
  - npm install -g qiniu-upload-tool
  - npm install
  - npm run build
  - ls ./build
  - qiniu-upload
  - export
  - docker login --username=zindex@muxi -p $DOCKER_PWD registry.cn-shenzhen.aliyuncs.com 
  - docker build . -t registry.cn-shenzhen.aliyuncs.com/muxi_site/workbench_fe:$TRAVIS_TAG
  - docker push registry.cn-shenzhen.aliyuncs.com/muxi_site/workbench_fe:$TRAVIS_TAG
script:
  - echo "hello world"