if: tag =~ /^release/
language: node_js
node_js:
  - "node"
env:
  - INLINE_RUNTIME_CHUNK=false REACT_APP_VERSION=$TRAVIS_TAG
cache: npm
services:
  - docker
install:
  - npm install -g qiniu-upload-tool muxi-react-scripts
  - npm install
  - npm run build
  - ls ./build
  - rm ./build/precache-manifest.*.js
  - qiniu-upload push -z huad -p ./build -b ccnustatic -f workbench -r yes
  - export
  - echo "$DOCKER_PWD" | docker login --username=zindex@muxi --password-stdin registry.cn-hongkong.aliyuncs.com
  - docker build . -t registry.cn-hongkong.aliyuncs.com/muxiauth/workbench_fe:$TRAVIS_TAG
  - docker push registry.cn-hongkong.aliyuncs.com/muxiauth/workbench_fe:$TRAVIS_TAG
script:
  - sh ./afterBuild.sh